apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: kube-prometheus-stack
  namespace: argocd
spec: 
  project: default
  source: 
    chart: bitnami/kube-prometheus
    repoURL: "https://charts.bitnami.com/bitnami"
    targetRevision: 8.1.11 
    helm:
     releaseName: kube-prometheus-stack
  destination: 
    namespace: kubbbe
    server: "https://kubernetes.default.svc"
  
  
  
  
  syncPolicy:
    syncOptions:
      - CreateNamespace=true

